# Generated by Django 3.2.8 on 2021-10-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('is_login', models.BooleanField(default=False)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('is_login', models.BooleanField(default=False)),
                ('delivery_address', models.TextField()),
            ],
        ),
    ]
