# Generated by Django 3.2.8 on 2021-10-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormDashApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_login',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_login',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
