# Generated by Django 3.2.8 on 2021-11-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormDashApp', '0004_menuitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('restaurant_pic', models.ImageField(upload_to='uploads/restaurant_pics/')),
            ],
        ),
    ]
