# Generated by Django 3.2.8 on 2021-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormDashApp', '0005_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
